config setup
    charondebug="ike 2, knl 2, cfg 2"
    uniqueids=no

conn site-to-site
    auto=start
    type=tunnel
    keyexchange=ikev1
    authby=secret
    
    # Site-A (Mannheim)
    left=10.255.0.10
    leftsubnet=10.0.1.0/24
    leftid=@site-a.mannheim
    leftfirewall=yes
    
    # Site-B (Heidelberg)
    right=10.255.0.20
    rightsubnet=10.0.2.0/24
    rightid=@site-b.heidelberg
    
    # Phase 1 (IKE)
    ike=aes256-sha256-modp2048!
    ikelifetime=86400s
    
    # Phase 2 (IPSec)
    esp=aes256-sha256-modp2048!
    lifetime=3600s
    keyingtries=%forever
    
    # DPD (Dead Peer Detection)
    dpdaction=restart
    dpddelay=30s
    dpdtimeout=120s
